server:
  port: 8080

spring:
  application:
    name: pain_helper_back
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pain_management_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        type:
          preferred_enum_type: string
  data:
    mongodb:
      uri: ${LOGGING_MONGODB_URI:mongodb://localhost:27017/analyticsdb}
      auto-index-creation: true
