@startuml
' AS-IS Components inside Monolith and touchpoints
skinparam monochrome true
skinparam componentStyle rectangle

package "Monolith" {
  [Admin]
  [Doctor]
  [Nurse]
  [Anesthesiologist]
  [Reporting (internal)]
  [Analytics (Mongo)]
  [External EMR Integration]
  [EMR Recalculation]
  [WebSocket Notifications]
  [Common/Persons (Login)]
}

[External EMR Integration] --> [EMR Recalculation] : EMR updates
[Common/Persons (Login)] --> [Analytics (Mongo)] : publish domain events
[Reporting (internal)] --> PG : query/aggregate
[Analytics (Mongo)] --> MONGO : save events/logs
[EMR Recalculation] --> [WebSocket Notifications] : notify UI

queue "Kafka" as Kafka
Kafka --> [EMR Recalculation] : emr.changes
[External EMR Integration] --> FHIR : HAPI FHIR HTTP

storage "Postgres Main" as PG
storage "Mongo analyticsdb" as MONGO
component FHIR
@enduml
